# Please modify the paths according to your own environment.
base_dir: '/path/to/base'
input_dir: '/path/to/raw_data'
output_dir: '/path/to/QC_output'
trimmed_data_path: '/path/to/Trim_data'
trimmomatic_path: '$EBROOTTRIMMOMATIC/trimmomatic-0.39.jar'
adapters_path: '/path/to/adapters.fa'
fastqc_path: 'fastqc'
# multiqc_path: 'multiqc'
--prokka_path: 'prokka'
--prokka_db_path: '/path/to/prokka_db'
min_contig_length: 1000
filtered_contigs_dir: '/path/to/Assembly/contigs/filtered_contigs'
annotation_output_dir: '/path/to/Annotation'

