# Please modify the paths according to your own environment.
base_dir: '/lustre04/scratch/zhangbin/HolmGenome'
input_dir: '/lustre04/scratch/zhangbin/HolmGenome/data'
output_dir: '/lustre04/scratch/zhangbin/HolmGenome/data'
# trimmed_data_path: '/path/to/Trim_data'
# trimmomatic_path: '$EBROOTTRIMMOMATIC/trimmomatic-0.39.jar'
#trimmomatic_path: 'trimmomatic'
trimmomatic_path: '$EBROOTTRIMMOMATIC/trimmomatic-0.39.jar'
adapters_path: '/lustre04/scratch/zhangbin/db/adapters.fa'

#adapters_path: '/lustre04/scratch/zhangbin/db/adapters.fa'
fastqc_path: 'fastqc'
# multiqc_path: 'multiqc'
# --prokka_path: 'prokka'
--prokka_db_path: '/lustre04/scratch/zhangbin/db/prokka/prokka_db'
min_contig_length: 1000
filtered_contigs_dir: '/lustre04/scratch/zhangbin/HolmGenome/data'
annotation_output_dir: '/lustre04/scratch/zhangbin/HolmGenome/data'

